name-template: 'v$RESOLVED_VERSION 🎉'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'

change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`#@'

version-resolver:
  major:
    labels: [ 'major' ]
  minor:
    labels: [ 'minor' ]
  patch:
    labels: [ 'patch' ]
  default: patch

template: |
  ## 🚀 What’s Changed
  $CHANGES

  ## 👥 Contributors
  $CONTRIBUTORS
